SURFACE_TOP_MARGIN = 20
SURFACE_BOTTOM_MARGIN = SURFACE_TOP_MARGIN
SURFACE_LEFT_MARGIN = SURFACE_TOP_MARGIN
SURFACE_RIGHT_MARGIN = SURFACE_TOP_MARGIN

POOL_TEXT_WIDTH = 100


LANE_TEXT_WIDTH = 50
LANE_TEXT_HEIGHT = 20
LANE_SHAPE_TOP_MARGIN = 50
LANE_SHAPE_BOTTOM_MARGIN = 50
LANE_SHAPE_LEFT_MARGIN = 30
LANE_SHAPE_RIGHT_MARGIN = 30

HSPACE_BETWEEN_SHAPES = 50
VSPACE_BETWEEN_SHAPES = 40

VSPACE_BETWEEN_LANES = 5
