from processpiper import ProcessMap, EventType, ActivityType, GatewayType

# with ProcessMap("This is a test diagram", colour_theme="GREENTURTLE") as my_process_map:
#     with my_process_map.add_lane("Customer") as lane1:
#         start = lane1.add_element("start", EventType.START)
#         br1 = lane1.add_element("Branch 1", GatewayType.EXCLUSIVE)
#         # br2 = lane1.add_element("Branch 2", GatewayType.EXCLUSIVE)
#         # br3 = lane1.add_element("Branch 2", GatewayType.EXCLUSIVE)
#         do = lane1.add_element("Do something", ActivityType.TASK)
#         end = lane1.add_element("end", EventType.END)
#         # start.connect(br1).connect(br2).connect(br3).connect(do).connect(end)
#         # br1.connect(br2).connect(br3).connect(do).connect(end)
#         start.connect(br1).connect(do).connect(end)

#     my_process_map.draw()
#     my_process_map.save("src/test01.png")


with ProcessMap("Pizza Order Process", colour_theme="BLUEMOUNTAIN") as my_process_map:
    with my_process_map.add_lane("Customer") as lane1:
        start = lane1.add_element("start", EventType.START)
        browse_website = lane1.add_element(
            "Browse PizzaPiper website", ActivityType.TASK
        )
        order_pizza = lane1.add_element("Order a pizza", ActivityType.TASK)
        make_payment = lane1.add_element("Make payment", ActivityType.TASK)
        receive_pizza = lane1.add_element("Receive pizza", ActivityType.TASK)
        end = lane1.add_element("end", EventType.END)
    with my_process_map.add_pool("Pizza Piper Enterprise") as pool1:
        with pool1.add_lane("Pizza Shop") as lane2:
            receive_order = lane2.add_element("Receive order", ActivityType.TASK)
            bake_pizza = lane2.add_element("Bake pizza", ActivityType.TASK)
            pizza_ready = lane2.add_element("Pizza ready?", GatewayType.EXCLUSIVE)
        with pool1.add_lane("Pizza Delivery") as lane3:
            deliver_pizza = lane3.add_element("Deliver pizza", ActivityType.TASK)
        start.connect(browse_website)
        browse_website.connect(order_pizza)
        order_pizza.connect(make_payment)
        make_payment.connect(receive_order, "Order details")
        receive_order.connect(bake_pizza)
        bake_pizza.connect(pizza_ready)
        pizza_ready.connect(deliver_pizza, "Yes")
        deliver_pizza.connect(receive_pizza, "Freshly baked \npizza")
        pizza_ready.connect(bake_pizza, "No")
        receive_pizza.connect(end)
    my_process_map.set_footer(" Generated by Process Piper")
    my_process_map.draw()
    my_process_map.save("images/test/pizza-order-process.png")
