from .processpiper import text2diagram


def test_promo():
    input_syntax = """
    title: Sample Test Process
    colourtheme: GREENTURTLE
    lane: End User
        (start) as start
        [Enter Keyword] as enter_keyword
        (end) as end
        
    start->enter_keyword->end
    """

    # input_syntax = """
    # title: Pizza Order Process
    #             colourtheme: BLUEMOUNTAIN
    #             lane: Customer
    #                     (start) as start
    #                     [Browse PizzaPiper website] as browse_website
    #                     [Order a pizza] as order_pizza
    #                     [Make payment] as make_payment
    #                     [Receive pizza] as receive_pizza
    #                     (end) as end
    #             pool: Pizza Piper Enterprise
    #                 lane: Pizza Shop
    #                     [Receive order] as receive_order
    #                     [Bake pizza] as bake_pizza
    #                     <Pizza ready?> as pizza_ready
    #                 lane: Pizza Delivery
    #                     [Deliver pizza] as deliver_pizza


    #         start->browse_website->order_pizza->make_payment
    #         make_payment->receive_order: Order details
    #         receive_order->bake_pizza
    #         bake_pizza->pizza_ready
    #         pizza_ready->deliver_pizza: Yes
    #         deliver_pizza->receive_pizza: Freshly baked \\npizza
    #         pizza_ready->bake_pizza: No
    #         receive_pizza->end


    #             footer: Generated by Process Piper
    #             """

    text2diagram.render(
        input_syntax, "images/test/pizza-order-process.png", show_code=True
    )


if __name__ == "__main__":
    test_promo()