from processpiper.text2diagram import render

input_syntax = """
title: Sample Test Process
    lane: End User
        (start) as start
        [Enter Keyword] as enter_keyword
        (end) as end
pool: System Search
    lane: Database System
        [Login] as login
        [Search Records] as search_records
        <Result Found?> as result_found
        [Display Result] as display_result
        [Logout] as logout
    lane: Log System
        [Log Error] as log_error

start->login->enter_keyword->search_records->result_found->display_result->logout->end
result_found->log_error->display_result

footer: Generated by ProcessPiper
"""

# input_syntax = """
# title: Test Process
# colourtheme: GREENTURTLE
# pool: Pool A
#     lane: Lane A
#         (start) as start
#         [Task 1] as task1
#         <branch 1> as branch1
#         [@subprocess Sub process 1] as subprocess1
#         <@parallel branch 2> as branch2
#         <@inclusive branch 3> as branch3
#         (end) as end
# pool: Pool B
#     lane: Lane B
#         (@timer schedule 1) as timer_schedule
#         (@intermediate schedule 2) as intermediate_schedule

# start->task1->branch1->subprocess1->branch2->branch3->end
# branch1->timer_schedule->intermediate_schedule->end

# footer: Generated by Process Piper
# """

render(input_syntax, "src/test01.png")
